ALTER TABLE Users ADD COLUMN tagline VARCHAR(255);
ALTER TABLE Users ADD COLUMN tweet_count INTEGER;
ALTER TABLE Users ADD COLUMN following_count INTEGER;
ALTER TABLE Users ADD COLUMN follower_count INTEGER;
